version: "3.8"

services:
  drf_ws_chat_api:
    image: drf_ws_chat_api:dev
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: drf_ws_chat_api
    ports:
      - "3001:8000"
    volumes:
      - ./backend:/code
    command:
      [
        "uvicorn",
        "backend.asgi:application",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
  drf_ws_chat_web:
    image: drf_ws_chat_web:dev
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: drf_ws_chat_web
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    command:
      [
        "npm",
        "start"
      ]
  