version: "3.8"

services:
  drf_ws_chat_api:
    image: drf_ws_chat_api:dev
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: drf_ws_chat_api
    ports:
      - "5080:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/code
    command:
      [
        "uvicorn",
        "backend.asgi:application",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
  