# Generated by Django 5.0.1 on 2024-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('from_uuid', models.UUIDField()),
                ('to_uuid', models.UUIDField()),
                ('delivered_on', models.DateTimeField(null=True)),
                ('seen_on', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
